@startuml 下载报表流程图
' !include themes/puml-theme-cerulean.puml
!include themes/puml-theme-materia.puml
' !include themes/puml-theme-materia-outline.puml
' !include themes/puml-theme-sketchy-outline.puml
' !include themes/puml-theme-sketchy.puml

title 下载报表流程图

skinparam ConditionEndStyle hline

:点击下载;
if (已经二次验证) then (是)
    if(验证过期？) then (是)
        :发送验证码进行二次验证;
        if (验证成功) then (是)
        else (否)
            :下载失败;
            stop
        endif
    else (否)
    endif
else (否)
    if(已经绑定二次\n验证的手机号) then (否)
        if (绑定二次验证手机号成功？) then (是)
        else (否)
            :下载失败;
            stop
        endif
    else (是)
        :发送验证码进行二次验证;
        if (验证成功) then (否)
            :下载失败;
            stop
        else (是)
        endif
    endif
endif

:下载报表;

stop
@enduml




@startuml 绑定二次验证手机号流程图
' !include themes/puml-theme-cerulean.puml
!include themes/puml-theme-materia.puml
' !include themes/puml-theme-cerulean-outline.puml
title 绑定二次验证手机号流程图

start
if (当前登录的是主账号) then (是)
    repeat :输入手机号;
    :发送验证码进行验证;
    backward :前端提示验证失败;
    repeat while (验证成功？) is (否) not (是)
    :绑定成功;
    detach
else (否)
    :绑定失败;
    detach
endif
@enduml


@startuml 用例图

' !include themes/puml-theme-cerulean.puml
!include themes/puml-theme-materia-outline.puml
' !include themes/puml-theme-superhero.puml

left to right direction

actor 顾问 as a #FF00FF

rectangle  用户 {
    actor "主账号" as c
    actor "子账号" as d #0000FF
}

package "系统" {
    usecase "绑定二次验证的手机" as UC1
    usecase "获取验证码" as UC2
    usecase "输入验证码并验证" as UC3
    usecase "下载报表" as UC4
}

c --> UC1
c --> UC2
c --> UC3
c --> UC4

d -[#0000FF]-> UC2
d -[#0000FF]-> UC3
d -[#0000FF]-> UC4

' a -[#FF00FF]-> UC4

UC2 ..\\ UC3
UC3 ..\\ UC4

@enduml